apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springbootapp
  name: {{ include "springbootapp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
          - containerPort: {{ .Values.containerPort }}