apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootapp
  name: {{ include "springbootapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: springbootapp
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
